### ISSUE TITLE
The plaintext of the ODBL license contains strange characters

### ISSUE THREAD

**Issue by sappelhoff** [okfn/opendatacommons.org#2]
See: https://github.com/okfn/opendatacommons.org/blob/0ce25eb9e637d894d525c74ea4efcbfceda6459d/content/licenses/odbl/odbl-10.txt#L59

In the rendered version it looks like this:

![image](https://user-images.githubusercontent.com/9084751/97070872-02dda280-15dc-11eb-8860-3af70db65721.png)

See: https://opendatacommons.org/licenses/odbl/1-0/

**Comment by chris48s** [comment]
:+1: fixed in https://github.com/okfn/opendatacommons.org/commit/6358ef1910c3f6b0c398e24257bdcb6baf6484fa

**Comment by sappelhoff** [comment]
thanks @chris48s
